version: '3.8'
services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  # Node api service
  app:
    build: .
    restart: always
    ports:
      - 4589:4589
    depends_on: 
      - db

volumes:
  mongo-data: